name: CI

on:
  push:
   branches:
     - master
  pull_request:
    branches: 
     - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: Lint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Run CheckStyle
      run: mvn checkstyle:checkstyle
    
   
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Unit Tests
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: clean
      run: mvn clean

    # compile
    - name: compile project
      run: mvn compile

    # run tests
    - name: run tests
      run: mvn test
